### ISSUE TITLE
 line 1059 of SSP. py: return np. reconcile ([offset_pts,...), calc_pts, corres_normal], axis=2)， The following error occurred: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 7920 and the array at index 2 has size 0。

### ISSUE THREAD

**Issue by notniuniu** [Runsong123/SSP#1]
I hope to reproduce your code, but there is an issue with line 1059 of SSP. py: return np. reconcile ([offset_pts,...), calc_pts, corres_normal], axis=2)， The following error occurred:
all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 7920 and the array at index 2 has size 0。
Debugging shows that the shapes of [offset_pts, calc_pts, Corres'normal] are (7920, 1000, 3), (7920, 1000, 1), and (0, 1000, 3), respectively.
The test target is 00010218_4769314c71814669ba5d3512_trimesh_113.xyz.npy in the ABC dataset.
May I ask which step may have caused the error? How should I solve it?

**Comment by notniuniu** [comment]
答案是因为00010218_4769314c71814669ba5d3512_trimesh_113.xyz.npy文件没有法向量，corres_normal试图读取法向量

**Comment by Runsong123** [comment]
> 答案是因为00010218_4769314c71814669ba5d3512_trimesh_113.xyz.npy文件没有法向量，corres_normal试图读取法向量

关于normal文件，你可以使用传统fitting方法 (e.g, PCA) ，或者使用learning-based的方法(默认用的Adafit)来生成unoriented  normal。
